# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'student_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

from client import login_student
from PyQt5.QtCore import Qt
from window import Ui_window
from student_register import Ui_student_register


class Ui_student_login(object):
    def setupUi(self, student_login):
        # 保留备份
        self.copy = student_login
        student_login.setObjectName("student_login")
        student_login.setFixedSize(311, 378)
        self.title = QtWidgets.QLabel(student_login)
        self.title.setGeometry(QtCore.QRect(70, 10, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.account_label = QtWidgets.QLabel(student_login)
        self.account_label.setGeometry(QtCore.QRect(30, 90, 58, 16))
        font = QtGui.QFont()
        font.setBold(True)
        self.account_label.setFont(font)
        self.account_label.setObjectName("account_label")
        self.password_label = QtWidgets.QLabel(student_login)
        self.password_label.setGeometry(QtCore.QRect(30, 140, 71, 16))
        font = QtGui.QFont()
        font.setBold(True)
        self.password_label.setFont(font)
        self.password_label.setObjectName("password_label")
        self.account = QtWidgets.QLineEdit(student_login)
        self.account.setGeometry(QtCore.QRect(120, 80, 141, 31))
        self.account.setObjectName("account")
        self.password = QtWidgets.QLineEdit(student_login)
        self.password.setGeometry(QtCore.QRect(120, 130, 141, 31))
        self.password.setObjectName("password")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.loginBtn = QtWidgets.QPushButton(student_login)
        self.loginBtn.setGeometry(QtCore.QRect(30, 200, 100, 32))
        self.loginBtn.setObjectName("loginBtn")
        self.registerBtn = QtWidgets.QPushButton(student_login)
        self.registerBtn.setGeometry(QtCore.QRect(160, 200, 100, 32))
        self.registerBtn.setObjectName("registerBtn")
        self.copyright = QtWidgets.QLabel(student_login)
        self.copyright.setGeometry(QtCore.QRect(20, 360, 281, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.copyright.setFont(font)
        self.copyright.setObjectName("copyright")
        self.copyright.setStyleSheet('color: gray')
        self.tip = QtWidgets.QLabel(student_login)
        self.tip.setGeometry(QtCore.QRect(30, 250, 231, 21))
        self.tip.setText("")
        self.tip.setObjectName("tip")

        self.retranslateUi(student_login)
        QtCore.QMetaObject.connectSlotsByName(student_login)

        self.__slot__()

    def retranslateUi(self, student_login):
        _translate = QtCore.QCoreApplication.translate
        student_login.setWindowTitle(_translate("student_login", "登录"))
        self.title.setText(_translate("student_login", "LessonMonitor"))
        self.account_label.setText(_translate("student_login", "Account"))
        self.password_label.setText(_translate("student_login", "Password"))
        self.loginBtn.setText(_translate("student_login", "登录"))
        self.registerBtn.setText(_translate("student_login", "注册"))
        self.copyright.setText(_translate("student_login", "©2023 NKCS Python大作业深渊一队, All rights reserved"))

    # 定义槽函数
    def __slot__(self):
        self.loginBtn.clicked.connect(self.login)
        self.registerBtn.clicked.connect(self.register)

    def login(self):
        account = self.account.text()
        password = self.password.text()

        if account == '' or password == '':
            QMessageBox.warning(self.copy, 'error', '账号或密码不能为空',
                                QMessageBox.Yes, QMessageBox.Yes)
            return

        response = login_student(account, password)
        if response == 'STUDENT_LOGIN_SUCCESS':
            # 注意，只有添加self声明才能正常显示下一个界面
            self.window = QtWidgets.QWidget()
            self.window_ui = Ui_window(account)
            self.window_ui.setupUi(self.window)
            self.window.show()

            self.copy.close()
            self.copy.destroy()

        elif response == 'STUDENT_LOGIN_FAIL':
            self.tip.setText('账号或密码错误，请重试!')
            self.tip.setStyleSheet('color: red;')
            self.tip.setAlignment(Qt.AlignCenter)

    def register(self):
        # 生成注册表单界面
        self.register_form = QtWidgets.QWidget()
        self.register_ui = Ui_student_register()
        self.register_ui.setupUi(self.register_form)
        self.register_form.show()

        self.copy.close()
        self.copy.destroy()


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    form = QtWidgets.QWidget()
    student_login = QtWidgets.QWidget()
    ui = Ui_student_login()
    ui.setupUi(student_login)
    student_login.show()
    sys.exit(app.exec_())
