# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'student_register.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

from client import register_student
from window import Ui_window
from PyQt5.QtCore import Qt


class Ui_student_register(object):
    def setupUi(self, student_register):
        self.copy = student_register
        student_register.setObjectName("student_register")
        student_register.setFixedSize(303, 381)
        self.password_label = QtWidgets.QLabel(student_register)
        self.password_label.setGeometry(QtCore.QRect(30, 140, 71, 16))
        font = QtGui.QFont()
        font.setBold(True)
        self.password_label.setFont(font)
        self.password_label.setObjectName("password_label")
        self.account = QtWidgets.QLineEdit(student_register)
        self.account.setGeometry(QtCore.QRect(120, 80, 141, 31))
        self.account.setObjectName("account")
        self.password = QtWidgets.QLineEdit(student_register)
        self.password.setGeometry(QtCore.QRect(120, 130, 141, 31))
        self.password.setObjectName("password")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.tip = QtWidgets.QLabel(student_register)
        self.tip.setGeometry(QtCore.QRect(30, 280, 231, 21))
        self.tip.setText("")
        self.tip.setObjectName("tip")
        self.loginBtn = QtWidgets.QPushButton(student_register)
        self.loginBtn.setGeometry(QtCore.QRect(30, 230, 100, 32))
        self.loginBtn.setObjectName("loginBtn")
        self.registerBtn = QtWidgets.QPushButton(student_register)
        self.registerBtn.setGeometry(QtCore.QRect(160, 230, 100, 32))
        self.registerBtn.setObjectName("registerBtn")
        self.copyright = QtWidgets.QLabel(student_register)
        self.copyright.setGeometry(QtCore.QRect(20, 360, 281, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.copyright.setFont(font)
        self.copyright.setObjectName("copyright")
        self.copyright.setStyleSheet("color: gray")
        self.title = QtWidgets.QLabel(student_register)
        self.title.setGeometry(QtCore.QRect(70, 10, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.account_label = QtWidgets.QLabel(student_register)
        self.account_label.setGeometry(QtCore.QRect(30, 90, 58, 16))
        font = QtGui.QFont()
        font.setBold(True)
        self.account_label.setFont(font)
        self.account_label.setObjectName("account_label")
        self.name_label = QtWidgets.QLabel(student_register)
        self.name_label.setGeometry(QtCore.QRect(30, 190, 58, 16))
        font = QtGui.QFont()
        font.setBold(True)
        self.name_label.setFont(font)
        self.name_label.setObjectName("name_label")
        self.name = QtWidgets.QLineEdit(student_register)
        self.name.setGeometry(QtCore.QRect(120, 180, 141, 31))
        self.name.setObjectName("name")

        self.retranslateUi(student_register)

        QtCore.QMetaObject.connectSlotsByName(student_register)
        self.__slot__()

    def retranslateUi(self, student_register):
        _translate = QtCore.QCoreApplication.translate
        student_register.setWindowTitle(_translate("student_register", "注册"))
        self.password_label.setText(_translate("student_register", "Password"))
        self.loginBtn.setText(_translate("student_register", "返回"))
        self.registerBtn.setText(_translate("student_register", "注册"))
        self.copyright.setText(_translate("student_register", "©2023 NKCS Python大作业深渊一队, All rights reserved"))
        self.title.setText(_translate("student_register", "LessonMonitor"))
        self.account_label.setText(_translate("student_register", "Account"))
        self.name_label.setText(_translate("student_register", "Name"))

    def __slot__(self):
        self.loginBtn.clicked.connect(self.comeBack)
        self.registerBtn.clicked.connect(self.register)

    def comeBack(self):
        import student_login

        self.login_form = QtWidgets.QWidget()
        self.login_ui = student_login.Ui_student_login()
        self.login_ui.setupUi(self.login_form)
        self.login_form.show()

        self.copy.close()
        self.copy.destroy()

    def register(self):
        account = self.account.text()
        password = self.password.text()
        name = self.name.text()

        if account == '' or password == '' or name == '':
            QMessageBox.warning(self.copy, 'error', '账号或密码不能为空',
                                QMessageBox.Yes, QMessageBox.Yes)
            return

        response = register_student(account, password, name)

        if response == 'STUDENT_ACCOUNT_REPEATED':
            self.tip.setText('账号已存在')
            self.tip.setStyleSheet('color: red')
            self.tip.setAlignment(Qt.AlignCenter)

        elif response == 'STUDENT_REGISTER_SUCCESS':
            self.window = QtWidgets.QWidget()
            self.window_ui = Ui_window(account)
            self.window_ui.setupUi(self.window)
            self.window.show()

            self.copy.close()
            self.copy.destroy()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    student_register = QtWidgets.QWidget()
    ui = Ui_student_register()
    ui.setupUi(student_register)
    student_register.show()
    sys.exit(app.exec_())
